repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.6.7
    hooks:
      - id: detect-secrets
        args: ['--exclude-files', 'checksums.sha256|lazy-lock.json|.*\.template.*|\.github/workflows/.*']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
